name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '51 4 * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.EAOJEC_TOKEN }}
          owner: MatsuriDayo
          base: dev
          head: dev
